packages:
  # whats app
  - 'app/*'
  # Shared libraries
  - 'packages/*'
  # Shared actions
  - .github/actions/*
  # App/Package templates
  - templates/*
  # Tooling related packages: CI, configs, etc.
  - tooling/*
