AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Chatx AWS CloudFormation template example.

Parameters:
  Environment:
    Type: String

Resources:
  ApiResource:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sam-templates/lambda-template.yaml
      Parameters:
        Environment: !Ref Environment
  DynamoDBResource:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./sam-templates/dynamodb-template.yaml
